import { GRAPH_API_VERSION, GRAPH_BASE_URL } from './meta-graph';

const RUPLOAD_BASE_URL = `https://rupload.facebook.com/video-upload/${GRAPH_API_VERSION}`;

export interface FacebookUploadParams {
  accessToken: string; // Page access token, see facebook-oauth.client.ts
  pageId: string; // Facebook Page id (SocialAccount.platformAccountId)
  // A public HTTPS URL Meta's servers fetch the video from themselves -
  // same presigned-URL pattern as Instagram Reels (packages/storage's
  // getPresignedDownloadUrl(), generated by publish-clip.worker.ts) - the
  // Video Reels API's upload step accepts a `file_url` header as an
  // alternative to POSTing the binary itself, so this avoids streaming the
  // clip's bytes through our own server a second time.
  videoUrl: string;
  caption: string;
}

export interface FacebookUploadResult {
  videoId: string;
}

interface GraphErrorBody {
  error?: { message?: string };
}

// Meta's 3-step "Video Reels" publishing flow for a Facebook Page - see
// CLAUDE.md's Publish Center section. Structurally the same "create, then
// finish/publish" shape as Instagram's container flow, but the middle step
// is a real upload-session handoff (POST to rupload.facebook.com) rather
// than a status poll - Meta's docs don't require polling before the finish
// call the way Instagram's container does.
export async function uploadFacebookReel(
  params: FacebookUploadParams,
): Promise<FacebookUploadResult> {
  const { accessToken, pageId, videoUrl, caption } = params;

  const startRes = await fetch(`${GRAPH_BASE_URL}/${pageId}/video_reels`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({ upload_phase: 'start', access_token: accessToken }),
  });
  const startBody = (await startRes.json()) as { video_id?: string; upload_url?: string } &
    GraphErrorBody;
  if (!startRes.ok || !startBody.video_id) {
    throw new Error(
      `Facebook video_reels start failed: ${startRes.status} ${startBody.error?.message ?? ''}`.trim(),
    );
  }
  const videoId = startBody.video_id;
  const uploadUrl = startBody.upload_url ?? `${RUPLOAD_BASE_URL}/${videoId}`;

  const uploadRes = await fetch(uploadUrl, {
    method: 'POST',
    headers: {
      Authorization: `OAuth ${accessToken}`,
      file_url: videoUrl,
    },
  });
  const uploadBody = (await uploadRes.json().catch(() => ({}))) as { success?: boolean } &
    GraphErrorBody;
  if (!uploadRes.ok || uploadBody.success === false) {
    throw new Error(
      `Facebook video upload failed: ${uploadRes.status} ${uploadBody.error?.message ?? ''}`.trim(),
    );
  }

  const finishRes = await fetch(`${GRAPH_BASE_URL}/${pageId}/video_reels`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({
      upload_phase: 'finish',
      video_id: videoId,
      video_state: 'PUBLISHED',
      description: caption,
      access_token: accessToken,
    }),
  });
  const finishBody = (await finishRes.json()) as { success?: boolean } & GraphErrorBody;
  if (!finishRes.ok || finishBody.success === false) {
    throw new Error(
      `Facebook video_reels finish failed: ${finishRes.status} ${finishBody.error?.message ?? ''}`.trim(),
    );
  }

  return { videoId };
}
