import { GRAPH_BASE_URL } from './meta-graph';

const POLL_INTERVAL_MS = 5_000;
const POLL_TIMEOUT_MS = 5 * 60 * 1000;

export interface InstagramUploadParams {
  accessToken: string; // Page access token, see instagram-oauth.client.ts
  igUserId: string; // Instagram Business Account id (SocialAccount.platformAccountId)
  // A public HTTPS URL Meta's servers fetch the video from themselves -
  // expected to be a short-lived presigned URL from packages/storage's
  // getPresignedDownloadUrl(), generated by the caller (publish-clip.worker.ts).
  videoUrl: string;
  caption: string;
}

export interface InstagramUploadResult {
  mediaId: string;
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

interface GraphErrorBody {
  error?: { message?: string };
}

// Instagram Content Publishing API's two-step "create a media container,
// then publish it" flow for Reels - see CLAUDE.md's Fase 6d "Instagram"
// section. Unlike YouTube/TikTok, there's no direct byte-upload option at
// all: the container is created by handing Meta's servers a public HTTPS
// URL to fetch the video from themselves, and container processing is
// asynchronous - it has to be polled until it reports FINISHED before
// media_publish can actually go through.
export async function uploadInstagramReel(
  params: InstagramUploadParams,
): Promise<InstagramUploadResult> {
  const { accessToken, igUserId, videoUrl, caption } = params;

  const createRes = await fetch(`${GRAPH_BASE_URL}/${igUserId}/media`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({
      media_type: 'REELS',
      video_url: videoUrl,
      caption,
      access_token: accessToken,
    }),
  });
  const createBody = (await createRes.json()) as { id?: string } & GraphErrorBody;
  if (!createRes.ok || !createBody.id) {
    throw new Error(
      `Instagram media container create failed: ${createRes.status} ${createBody.error?.message ?? ''}`.trim(),
    );
  }
  const containerId = createBody.id;

  const status = await pollContainerStatus(containerId, accessToken);
  if (status !== 'FINISHED') {
    throw new Error(`Instagram media container did not finish processing (status: ${status})`);
  }

  const publishRes = await fetch(`${GRAPH_BASE_URL}/${igUserId}/media_publish`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({ creation_id: containerId, access_token: accessToken }),
  });
  const publishBody = (await publishRes.json()) as { id?: string } & GraphErrorBody;
  if (!publishRes.ok || !publishBody.id) {
    throw new Error(
      `Instagram media_publish failed: ${publishRes.status} ${publishBody.error?.message ?? ''}`.trim(),
    );
  }

  return { mediaId: publishBody.id };
}

// Terminal states per Meta's docs: FINISHED (ready to publish), ERROR/
// EXPIRED (never will be) - anything else (IN_PROGRESS, PUBLISHED from a
// stale check) keeps polling until POLL_TIMEOUT_MS is exhausted.
async function pollContainerStatus(containerId: string, accessToken: string): Promise<string> {
  const deadline = Date.now() + POLL_TIMEOUT_MS;
  while (Date.now() < deadline) {
    const url = new URL(`${GRAPH_BASE_URL}/${containerId}`);
    url.searchParams.set('fields', 'status_code');
    url.searchParams.set('access_token', accessToken);
    const res = await fetch(url);
    const body = (await res.json()) as { status_code?: string } & GraphErrorBody;
    if (!res.ok) {
      throw new Error(
        `Instagram container status check failed: ${res.status} ${body.error?.message ?? ''}`.trim(),
      );
    }
    if (
      body.status_code === 'FINISHED' ||
      body.status_code === 'ERROR' ||
      body.status_code === 'EXPIRED'
    ) {
      return body.status_code;
    }
    await sleep(POLL_INTERVAL_MS);
  }
  throw new Error('Instagram media container timed out waiting to finish processing');
}
