import { THREADS_GRAPH_BASE_URL } from './threads-graph';

const POLL_INTERVAL_MS = 5_000;
const POLL_TIMEOUT_MS = 5 * 60 * 1000;

export interface ThreadsUploadParams {
  accessToken: string; // long-lived Threads user access token, see threads-oauth.client.ts
  threadsUserId: string; // SocialAccount.platformAccountId
  // A public HTTPS URL Meta's servers fetch the video from themselves - same
  // presigned-URL pattern as Instagram Reels (packages/storage's
  // getPresignedDownloadUrl(), generated by publish-clip.worker.ts).
  videoUrl: string;
  text: string;
}

export interface ThreadsUploadResult {
  threadsPostId: string;
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

interface ThreadsErrorBody {
  error?: { message?: string } | string;
}

function errorMessageOf(body: ThreadsErrorBody): string {
  if (typeof body.error === 'string') return body.error;
  return body.error?.message ?? '';
}

// Threads' own "create a media container, then publish it" flow - the same
// container-create -> poll -> publish shape as Instagram Reels
// (instagram-upload.client.ts), just POST /{threads-user-id}/threads then
// POST /{threads-user-id}/threads_publish rather than Instagram's /media
// and /media_publish. See CLAUDE.md's Publish Center section.
export async function uploadThreadsVideo(
  params: ThreadsUploadParams,
): Promise<ThreadsUploadResult> {
  const { accessToken, threadsUserId, videoUrl, text } = params;

  const createRes = await fetch(`${THREADS_GRAPH_BASE_URL}/${threadsUserId}/threads`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({
      media_type: 'VIDEO',
      video_url: videoUrl,
      text,
      access_token: accessToken,
    }),
  });
  const createBody = (await createRes.json()) as { id?: string } & ThreadsErrorBody;
  if (!createRes.ok || !createBody.id) {
    throw new Error(
      `Threads media container create failed: ${createRes.status} ${errorMessageOf(createBody)}`.trim(),
    );
  }
  const containerId = createBody.id;

  const status = await pollContainerStatus(containerId, accessToken);
  if (status !== 'FINISHED') {
    throw new Error(`Threads media container did not finish processing (status: ${status})`);
  }

  const publishRes = await fetch(`${THREADS_GRAPH_BASE_URL}/${threadsUserId}/threads_publish`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({ creation_id: containerId, access_token: accessToken }),
  });
  const publishBody = (await publishRes.json()) as { id?: string } & ThreadsErrorBody;
  if (!publishRes.ok || !publishBody.id) {
    throw new Error(
      `Threads threads_publish failed: ${publishRes.status} ${errorMessageOf(publishBody)}`.trim(),
    );
  }

  return { threadsPostId: publishBody.id };
}

// Same terminal-state polling shape as Instagram's pollContainerStatus() -
// Meta's Threads docs recommend waiting at least 30s before publishing
// rather than documenting exact status values, so this reuses Instagram's
// FINISHED/ERROR/EXPIRED convention (the general Meta container-processing
// model) - flagged in CLAUDE.md's Publish Center section as needing
// real-credential verification, same as the rest of this trio.
async function pollContainerStatus(containerId: string, accessToken: string): Promise<string> {
  const deadline = Date.now() + POLL_TIMEOUT_MS;
  while (Date.now() < deadline) {
    const url = new URL(`${THREADS_GRAPH_BASE_URL}/${containerId}`);
    url.searchParams.set('fields', 'status');
    url.searchParams.set('access_token', accessToken);
    const res = await fetch(url);
    const body = (await res.json()) as { status?: string } & ThreadsErrorBody;
    if (!res.ok) {
      throw new Error(
        `Threads container status check failed: ${res.status} ${errorMessageOf(body)}`.trim(),
      );
    }
    if (body.status === 'FINISHED' || body.status === 'ERROR' || body.status === 'EXPIRED') {
      return body.status;
    }
    await sleep(POLL_INTERVAL_MS);
  }
  throw new Error('Threads media container timed out waiting to finish processing');
}
